version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.15
    commands:
      - echo Installing source NPM dependencies
      - npm ci
  pre_build:
    commands:
      - echo Generating Prisma Client
      - npx prisma generate
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - dist/**/*
    - prisma/schema.prisma
    - prisma/migrations/**/*
    - prisma/seeders/*
    - package.json
    - node_modules/**/*
    - .ebextensions/**/*
    - templates/**/*
# cache:
#   paths:
#     - node_modules
