version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.15
    commands:
      - npm ci
  pre_build:
    commands:
      - npx prisma generate
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  type: zip
  files:
    - dist/**/*
    - prisma/**
    - package.json
    - node_modules/**
    - .ebextensions
cache:
  paths:
    - node_modules
