name: 'postgresql-dev'
services:
  db:
    image: 'postgres'
    container_name: 'postgresql-dev'
    restart: 'on-failure'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=emed-db
    volumes:
      - 'emed-db-data:/var/lib/postgresql/data'

volumes:
  emed-db-data: